security:
  oauth2:
    resource:
      userInfoUri: http://authentication-service:9000/user
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
        kafka:
          binder:
            zkNodes: localhost
            brokers: localhost
